import { createContext, useContext, useState, useEffect } from 'react';

// Exported (not just wrapped by useLanguage) so ErrorBoundary — a class
// component sitting both inside and outside LanguageProvider in App.jsx —
// can attach it via `static contextType` for its inline fallback branch.
export const LanguageContext = createContext();

const translations = {
  uz: {
    login: 'Kirish',
    logout: 'Chiqish',
    profile: 'Profil',
    dashboard: 'Bosh Sahifa',
    welcome: 'Xush kelibsiz',
    username: 'Foydalanuvchi Nomi',
    password: 'Parol',
    currentPassword: 'Joriy Parol',
    newPassword: 'Yangi Parol',
    confirmPassword: 'Parolni Tasdiqlash',
    changePassword: 'Parolni O\'zgartirish',
    loginFailed: 'Kirish muvaffaqiyatsiz',
    passwordChanged: 'Parol o\'zgartirildi',
    warrantyForm: 'Kafolat daftari',
    submitForm: 'Yuborish',
    formSubmitted: 'Muvaffaqiyatli yuborildi',
    myProfile: 'Mening Profilim',
    users: 'Foydalanuvchilar',
    manageUsers: 'Foydalanuvchilarni Boshqarish',
    createUser: 'Yangi Foydalanuvchi Yaratish',
    editUser: 'Tahrirlash',
    deleteUser: 'O\'chirish',
    warrantyForms: 'Kafolat daftarlari',
    searchForms: 'Qidirish',
    exportExcel: 'Excel Eksport',
    totalForms: 'Jami Shakslar',
    totalEmployees: 'Jami Xodimlar',
    warrantyInfo: 'Garantiya Ma\'lumotlari',
    vehicleInfo: 'Avtomobil Ma\'lumotlari',
    equipmentInfo: 'Uskunalar Ma\'lumotlari',
    region: 'Viloyat',
    city: 'Shahar',
    district: 'Tuman',
    organizationName: 'Tashkilot Nomi',
    organizationPhone: 'Tashkilot Tel',
    installerName: 'O\'rnatuvchi Ismi',
    installerPhone: "O'rnatuvchi Telefoni",
    warrantyBookNumber: 'Garantiya Raqami',
    warrantyNumberPendingSync: "Yuborilgandan so'ng avtomatik tayinlanadi",
    valYearRange: "Ishlab chiqarilgan yil 1950 dan keyin va kelajakda bo'lmasligi kerak",
    valMileageRange: "Probeg noto'g'ri qiymatga ega",
    valInstallationDateRange: "O'rnatish sanasi 2015-yildan keyin va kelajakda bo'lmasligi kerak",
    installationDate: 'O\'rnatish Sanasi',
    vehicleBrand: 'Avtomobil Brendi',
    vehicleModel: 'Model',
    vehicleName: 'Avtomobil',
    vehicleNamePlaceholder: 'Masalan: Chevrolet Cobalt',
    productionYear: 'Yil',
    plateNumber: 'Davlat raqami',
    plateNumberOptionalHint: "Agar hali mavjud bo'lmasa, bo'sh qoldiring",
    vinNumber: 'VIN',
    engineVolume: 'Dvigatel Hajmi',
    enginePower: 'Dvigatel Quvvati',
    mileage: 'Probeg',
    ownerName: 'Eganing Ismi',
    ownerPhone: 'Eganing Tel',
    reducer: 'Redyuktor',
    cylinder: 'Tsilinder',
    controller: 'STAG Kontrolyeri',
    injectorRail: 'Injektor Relsi',
    fuelType: 'Yonilgi Turi',
    manufacturer: 'Ishlab Chiqaruvchi',
    serialNumber: 'Seriya Raqami',
    serialVinNumber: 'Seriya/VIN raqami',
    barcodeScanOrType: "Shtrix-kodni skanerlang yoki kiriting",
    selectProductFirst: "Avval mahsulotni tanlang",
    productSearchPlaceholder: "Mahsulot nomini kiriting (masalan: STAG)",
    selectBrandFirst: "Avval brendni tanlang",
    selectOption: 'Tanlang',
    loadingResults: 'Qidirilmoqda...',
    noResultsFound: 'Hech narsa topilmadi',
    vehicleNotInCatalogHint: "Ro'yxatda yo'q — kiritgan matningiz baribir saqlanadi",
    valProductRequired: 'Mahsulotni tanlang',
    // ── Manual Verification — HISTORICAL admin review UI only (the active
    // installer workflow was disabled 2026-08-26 and its keys removed;
    // these remain for viewing/resolving old records) ──
    sellerName: 'Sotuvchi ismi',
    sellerPhone: 'Sotuvchi telefon raqami',
    verificationComment: 'Izoh',
    verificationPhotoOptional: 'Rasm (ixtiyoriy)',
    verificationStatusColumn: 'Tekshiruv holati',
    verificationFilterAll: 'Barcha tekshiruvlar',
    verificationStatusPending: "Ko'rib chiqilmoqda",
    verificationStatusApproved: 'Tasdiqlangan',
    verificationStatusRejected: 'Rad etilgan',
    approveVerificationTitle: "Qo'lda tekshirishni tasdiqlash",
    approveVerificationMessage: "Ushbu uskunani qo'lda tekshirishni tasdiqlashga ishonchingiz komilmi? Ballar darhol beriladi.",
    verificationApproved: "Qo'lda tekshirish tasdiqlandi",
    verificationRejected: "Qo'lda tekshirish rad etildi",
    rejectVerificationTitle: "Qo'lda tekshirishni rad etish",
    rejectVerificationMessage: "Ushbu uskunani qo'lda tekshirishni rad etishga ishonchingiz komilmi? Kafolat rad etilgan deb belgilanadi.",
    // Warranty status workflow — the warranty form's own lifecycle,
    // separate from verification* keys above (Manual Verification).
    warrantyStatusColumn: 'Kafolat holati',
    warrantyStatusPending: "Ko'rib chiqilmoqda",
    warrantyStatusSuccessful: 'Muvaffaqiyatli',
    warrantyStatusRejected: 'Rad etilgan',
    approveWarrantyTitle: 'Kafolatni tasdiqlash',
    approveWarrantyMessage: 'Ushbu kafolatni tasdiqlashga ishonchingiz komilmi? Tasdiqlangandan so\'ng u avtomatik ravishda EasyGas tizimiga yuboriladi.',
    rejectWarrantyTitle: 'Kafolatni rad etish',
    rejectWarrantyMessage: 'Ushbu kafolatni rad etishga ishonchingiz komilmi? Rad etilgan kafolatlar hech qachon EasyGas tizimiga yuborilmaydi.',
    warrantyApproved: 'Kafolat tasdiqlandi',
    warrantyRejected: 'Kafolat rad etildi',
    viewEasyGasWarranty: 'EasyGas kafolatini ko\'rish',
    viewEasyGasWarrantyShort: 'EasyGas',
    easyGasSyncFailed: 'EasyGas tizimiga yuborishda xatolik yuz berdi',
    // EasyGas claim_url QR presentation
    easyGasWarrantyTitle: 'EasyGas kafolati',
    scanWarrantyQrHint: 'Kafolatni ochish uchun QR kodni telefon kamerasi bilan skanerlang',
    openWarrantyLink: 'Havolani ochish',
    easyGasSyncFailedInstaller: 'EasyGas kafolatini yaratishda xatolik yuz berdi',
    easyGasSyncErrorLabel: 'Xatolik tafsiloti',
    // ── Customer lookup (Mijozni topish, Beta-1) ──
    customerLookup: 'Mijozni topish',
    customerLookupDesc: "Mijoz telefon raqami orqali o'rnatilgan uskunalarni va kafolatlarni toping",
    searchAction: 'Qidirish',
    noCustomerFound: 'Mijoz topilmadi',
    noCustomerFoundDesc: "Bu raqam bo'yicha kafolat topilmadi. Raqamni tekshirib, qayta urinib ko'ring.",
    lookupFailed: 'Qidirishda xatolik yuz berdi',
    installedEquipment: "O'rnatilgan uskunalar",
    installerLabel: 'Usta',
    branchLabel: 'Filial',
    serialLabel: 'Seriya',
    notProvided: 'Kiritilmagan',
    // ── Searchable branch selector (Beta-1) ──
    branchSearchPlaceholder: "Filial kodi yoki nomi bo'yicha qidiring",
    branchSearchOptionalPlaceholder: "Filial (ixtiyoriy) — kodi yoki nomi bo'yicha qidiring",
    noBranchesFound: 'Filial topilmadi',
    // ── Optional cylinder (Beta-3) ──
    optionalLabel: 'Ixtiyoriy',
    addCylinderAction: "Tsilindr qo'shish",
    removeCylinderAction: 'Tsilindrni olib tashlash',
    cylinderNotAdded: 'Tsilindr kiritilmagan',
    typedCylinderInfo: "Qo'lda kiritilgan tsilindr",
    // ── Branch business-group classification (Beta-2) ──
    branchTypeLabel: 'Servis turi',
    branchTypeFilterAll: 'Barchasi',
    branchTypeEasyGas: 'EasyGas',
    branchTypeStagService: 'STAG Service',
    branchTypeOtherService: 'Boshqa servislar',
    branchTypeUnclassified: 'Tayinlanmagan',
    usernameFormatHelperTitle: 'Username formati: prefix_ism_viloyat_filial',
    usernamePrefixLegend: 'eg = EasyGas · st = STAG Service · bs = Boshqa servis',
    usernameBranchMismatchHint: "Username'dagi filial kodi tanlangan filialga mos kelmaydi",
    // ── Beta-2.1: registration approval + explicit reclassification ──
    applicantUsernameLabel: "Ariza beruvchining username'i",
    approveRequestFinalUsername: 'Yakuniy managed username',
    approveRequestUsernameHint: "Ariza beruvchining o'z username'i yakuniy hisob bo'lmaydi — administrator managed username kiritadi.",
    reclassifyBranchAction: 'Servis turini tuzatish',
    reclassifyBranchWarning: "Bu istisno tuzatish amali: filial servis turi odatda xodimlarni ro'yxatga olish orqali belgilanadi. Faqat noto'g'ri belgilangan holatni tuzatish uchun foydalaning.",
    currentTypeLabel: 'Joriy tur',
    newTypeLabel: 'Yangi tur',
    branchReclassified: 'Filial servis turi yangilandi',
    easyGasInconsistentState: 'EasyGas holati nomuvofiq: sinxronizatsiya muvaffaqiyatli deb belgilangan, biroq kafolat havolasi mavjud emas.',
    // EasyGas /verify lookup (admin catalog sync page) — requires one of
    // phone/vin/serial, entered explicitly by the admin
    verifyEasyGasTitle: 'EasyGas tekshiruvi',
    verifyEasyGasHint: "Tekshirish uchun telefon raqami, VIN yoki seriya raqamidan bittasini kiriting",
    verifyTypePhone: 'Telefon raqami',
    verifyTypeVin: 'VIN',
    verifyTypeSerial: 'Seriya raqami',
    verifyRunButton: 'Tekshirish',
    verifyOkResult: "So'rov bajarildi — javob quyida",
    verifyFailedResult: 'Tekshirish muvaffaqiyatsiz tugadi',
    save: 'Saqlash',
    cancel: 'Bekor',
    delete: 'O\'chirish',
    view: 'Ko\'rish',
    clear: 'Tozalash',
    loading: 'Yuklanmoqda...',
    error: 'Xato',
    success: 'Muvaffaqiyat',
    search: 'Qidirish',
    filter: 'Filter',
    employee: 'Xodim',
    required: 'Majburiy',
    date: 'Sana',
    phone: 'Telefon',
    actions: 'Amallar',
    exportData: 'Ma\'lumotlarni Eksport Qilish',
    timePeriod: 'Vaqt Oralig\'i',
    loginTitle: "Sistema boshqaruv kafolati",
    empAlert: "O'rnatishingiz uchun kafolat formasi tafsilotlarini to'ldiring",
    empProfile: "Hisob sozlamalaringiz boshqaring",
    empAccount: "Hisob ma'lumotlari",
    empAccountDetails: "Hisobingizning asosiy ma'lumotlari",
    myWarrantyHistory: "Mening Kafolatlarim",
    myWarrantyHistoryDesc: "Yuborilgan kafolat daftarlarim",
    noWarrantyHistory: "Kafolat tarixi mavjud emas",
    noWarrantyHistoryDesc: "Siz hali kafolat formasi yuklamagansiz",
    editWarranty: "Tahrirlash",
    editWarrantyTitle: "Kafolatni Tahrirlash",
    saveChanges: "O'zgarishlarni Saqlash",
    editExpired: "24 soat o'tdi, tahrirlash mumkin emas",
    dashboardSubtitle: "Xush kelibsiz! Tizim holati va so'nggi faoliyat shu yerda.",
    thisWeek: 'Shu hafta',
    topBranch: 'Yetakchi filial',
    submissionsTrend: "So'nggi 14 kunlik dinamika",
    fuelTypeBreakdown: "Yoqilg'i turi taqsimoti",
    topOrganizations: 'Faol tashkilotlar',
    recentSubmissions: 'So\'nggi kafolatlar',
    noRecentSubmissions: "Hali kafolat topshirilmagan",
    noRecentSubmissionsDesc: "Xodimlar kafolat daftarini topshirganda shu yerda ko'rinadi",
    viewAll: "Barchasini ko'rish",
    quickActions: 'Tezkor amallar',
    qaViewForms: 'Kafolat daftarlarini ko\'rish',
    qaManageUsers: 'Foydalanuvchilarni boshqarish',
    qaExportReport: 'Hisobotni eksport qilish',
    notifications: 'Bildirishnomalar',
    noNotifications: "Yangi bildirishnoma yo'q",
    noNotificationsDesc: "Barchasi nazoratda. Yangi voqealar shu yerda ko'rinadi.",
    systemStatus: 'Tizim holati',
    apiOnline: 'API ishlamoqda',
    databaseConnected: "Ma'lumotlar bazasi ulangan",
    lastSynced: 'Oxirgi yangilanish',
    refresh: 'Yangilash',
    vehicle: 'Avtomobil',
    owner: 'Egasi',
    branch: 'Filial',
    submissionsUnit: 'ta',
    navWarrantyHistory: 'Kafolat tarixi',
    searchPlaceholder: 'Sahifa qidirish...',
    searchNoResults: 'Hech narsa topilmadi',
    collapseSidebar: "Panelni yig'ish",
    expandSidebar: 'Panelni yoyish',
    myAccount: 'Mening hisobim',
    warrantyDetailsTitle: 'Kafolat tafsilotlari',
    searchFormsPlaceholder: "Davlat raqami, egasi yoki xodim bo'yicha qidiring",
    searchHistoryPlaceholder: "Davlat raqami yoki egasi bo'yicha qidiring",
    perPage: 'sahifada',
    allForms: 'Barcha shakllar',
    adminWarrantySubtitle: "Barcha kafolat daftarlarini boshqarish va ko'rish",
    filteredByInstallerLabel: "O'rnatuvchi bo'yicha filtrlangan",
    clearInstallerFilter: 'Barcha kafolatlarni ko\'rsatish',
    viewInstallerWarranties: 'Kafolatlarni ko\'rish',
    noFormsFound: 'Kafolat topilmadi',
    noFormsFoundDesc: "Qidiruv filtrlarini o'zgartirib ko'ring",
    deleteFormTitle: 'Formani o\'chirish',
    deleteFormMessage: "Ushbu kafolat formasini o'chirishga ishonchingiz komilmi? Bu amalni bekor qilib bo'lmaydi.",
    formDeleted: "Forma muvaffaqiyatli o'chirildi",
    formUpdated: 'Kafolat formasi muvaffaqiyatli yangilandi!',
    fillRequiredFields: "Barcha majburiy maydonlarni to'ldiring",
    editExpiresIn: 'Tahrirlash uchun qoldi',
    hoursShort: 's',
    successFormDesc: 'Kafolat formangiz muvaffaqiyatli qabul qilindi',
    sectionWarranty: 'Kafolat tafsilotlari',
    sectionVehicle: "Avtomobil haqida ma'lumot",
    sectionOwner: "Egasi haqida ma'lumot",
    sectionEquipment: 'Uskuna tafsilotlari',
    scanCertificate: 'Guvohnomani Skanerla',
    sectionComplete: "Barcha maydonlar to'ldirildi",
    selectPlaceholder: 'Tanlang...',
    fullName: "To'liq ism",
    signIn: 'Kirish',
    signingIn: 'Kirilmoqda...',
    signUp: "Ro'yxatdan o'tish",
    creatingAccount: 'Yaratilmoqda...',
    createAccount: 'Hisob yaratish',
    dontHaveAccount: "Hisobingiz yo'qmi?",
    alreadyHaveAccount: 'Allaqachon hisobingiz bormi?',
    usernamePlaceholder: 'Foydalanuvchi nomini kiriting',
    passwordPlaceholder: 'Parolni kiriting',
    chooseUsernamePlaceholder: 'Foydalanuvchi nomini tanlang',
    atLeast6CharsPlaceholder: 'Kamida 6 ta belgi',
    repeatPasswordPlaceholder: 'Parolni takrorlang',
    phoneOptional: 'Telefon (ixtiyoriy)',
    fullNamePlaceholder: "To'liq ismingizni kiriting",
    last7Days: 'Oxirgi 1 hafta',
    last30Days: 'Oxirgi 1 oy',
    last3Months: 'Oxirgi 3 oy',
    last6Months: 'Oxirgi 6 oy',
    last1Year: 'Oxirgi 1 yil',
    allData: 'Hammasi',
    security: 'Xavfsizlik sozlamalari',
    securityDesc: 'Parolingiz va xavfsizligingizni boshqaring',
    exportMyData: "Ma'lumotlarimni eksport qilish",
    exportMyDataDesc: "Kafolat formalarimni Excel formatida yuklab oling",
    downloadExcel: 'Excel yuklab olish',
    exportingLabel: 'Yuklanmoqda...',
    branchCode: 'Filial kodi',
    active: 'Faol',
    status: 'Holat',
    exportWarrantyDataDesc: 'Kafolat formalarini ixtiyoriy sana filtri bilan yuklab oling',
    exportToExcel: "Excel-ga eksport qilish",
    inactive: 'Faol emas',
    usersSubtitle: "Tizim foydalanuvchilarini va ruxsatlarini boshqarish",
    searchUsersPlaceholder: "Ism, foydalanuvchi nomi yoki filial bo'yicha qidiring",
    allStatuses: 'Barcha holatlar',
    noEmployeesYet: "Hali xodimlar yo'q",
    noEmployeesYetDesc: "Birinchi xodimni qo'shish uchun yuqoridagi tugmani bosing",
    noUsersMatch: 'Hech kim topilmadi',
    noUsersMatchDesc: "Qidiruv yoki filtrlarni o'zgartirib ko'ring",
    resetPasswordAction: 'Parolni tiklash',
    disableAction: 'Faolsizlantirish',
    disableUserTitle: 'Foydalanuvchini faolsizlantirish',
    disableUserMessage: 'Ushbu foydalanuvchini faolsizlantirishga ishonchingiz komilmi?',
    resetPasswordConfirmTitle: 'Parolni tiklash',
    resetPasswordConfirmMessage: "Yangi vaqtinchalik parol yaratiladi. Foydalanuvchi keyingi kirishda uni o'zgartirishi kerak bo'ladi.",
    userCreated: 'Foydalanuvchi muvaffaqiyatli yaratildi',
    userUpdated: 'Foydalanuvchi muvaffaqiyatli yangilandi',
    userDisabled: 'Foydalanuvchi faolsizlantirildi',
    newPasswordTitle: 'Yangi parol yaratildi',
    newPasswordDesc: "Ushbu parolni xodimga xavfsiz tarzda yetkazing. Uni qayta ko'rib bo'lmaydi.",
    copyToClipboard: 'Nusxalash',
    copied: 'Nusxalandi!',
    done: 'Tayyor',
    sessionExpiredMessage: 'Sessiya muddati tugadi. Iltimos, qayta kiring.',

    // ── Validation messages (Zod factory schemas) ──
    valFirstNameRequired: 'Ism kiritilishi shart',
    valLastNameRequired: 'Familiya kiritilishi shart',
    valFullNameRequired: "To'liq ism kiritilishi shart",
    valRegionRequired: 'Viloyatni tanlang',
    valDistrictRequired: 'Tumanni tanlang',
    valBranchRequired: 'Filialni tanlang',
    valPhoneInvalid: "Telefon raqami noto'g'ri (masalan: +998901234567)",
    valUsernameRequired: 'Foydalanuvchi nomini kiriting',
    valUsernameMinLength: "Foydalanuvchi nomi kamida 3 ta belgidan iborat bo'lishi kerak",
    valPasswordRequired: 'Parolni kiriting',
    valPasswordMinLength: "Parol kamida 6 ta belgidan iborat bo'lishi kerak",
    valConfirmPasswordRequired: 'Parolni tasdiqlang',
    valPasswordsMismatch: 'Parollar mos kelmadi',
    valCurrentPasswordRequired: 'Joriy parolni kiriting',
    valPhotoRequired: 'Shaxsiy rasm yuklash shart',
    valPhotoInvalidType: "Fayl formati noto'g'ri. Faqat JPG, PNG yoki WEBP",
    valPhotoTooLarge: "Fayl hajmi 5 MB dan oshmasligi kerak",
    fieldRequired: "Bu maydon to'ldirilishi shart",

    // ── Generic UI ──
    admin: 'Administrator',
    unableToLoadData: "Ma'lumotlarni yuklab bo'lmadi",
    unableToLoadProfile: "Profilni yuklab bo'lmadi",
    unableToLoadUsers: "Foydalanuvchilarni yuklab bo'lmadi",
    unableToLoadForms: "Kafolat daftarlarini yuklab bo'lmadi",
    unableToLoadHistory: "Tarixni yuklab bo'lmadi",
    unableToLoadDashboard: "Boshqaruv panelini yuklab bo'lmadi",
    unableToLoadRequests: "So'rovlarni yuklab bo'lmadi",
    tryAgain: 'Qayta urinish',
    close: 'Yopish',
    confirm: 'Tasdiqlash',
    somethingWentWrong: 'Nimadir xato ketdi',
    unexpectedErrorOnPage: 'Ushbu sahifada kutilmagan xatolik yuz berdi.',
    home: 'Bosh sahifa',
    refreshPage: 'Sahifani yangilash',
    breadcrumbAria: "Yo'l xaritasi",
    hidePassword: 'Parolni yashirish',
    showPassword: "Parolni ko'rsatish",
    previousPage: 'Oldingi sahifa',
    nextPage: 'Keyingi sahifa',
    closeMenu: 'Menyuni yopish',
    openMenu: 'Menyuni ochish',
    errorSubmittingForm: 'Formani yuborishda xatolik yuz berdi',

    // ── Registration form ──
    firstName: 'Ism',
    lastName: 'Familiya',
    firstNamePlaceholder: 'Ismingizni kiriting',
    lastNamePlaceholder: 'Familiyangizni kiriting',
    personalPhoto: 'Shaxsiy rasm',
    uploadPhoto: 'Rasm yuklash',
    removePhoto: "Rasmni o'chirish",
    changePhoto: 'Rasmni almashtirish',
    submitRequest: "So'rovni yuborish",
    submittingRequest: 'Yuborilmoqda...',
    registrationPendingTitle: "So'rov yuborildi",
    registrationPendingMessage: "O'rovingiz muvaffaqiyatli yuborildi.\nAdministrator tekshiruvdan so'ng siz bilan bog'lanadi.",
    backToLogin: 'Kirish sahifasiga qaytish',

    // ── Admin: Registration Requests ──
    registrationRequests: "So'rovlar",
    registrationRequestsSubtitle: "Yangi foydalanuvchi so'rovlarini ko'rib chiqish va tasdiqlash",
    searchRequestsPlaceholder: "Ism, foydalanuvchi nomi yoki filial bo'yicha qidiring",
    noRequestsYet: "Hali so'rovlar yo'q",
    noRequestsYetDesc: "Yangi ro'yxatdan o'tish so'rovlari shu yerda ko'rinadi",
    noRequestsMatch: 'Hech narsa topilmadi',
    noRequestsMatchDesc: "Qidiruv yoki filtrlarni o'zgartirib ko'ring",
    statusPending: 'Kutilmoqda',
    statusApproved: 'Tasdiqlangan',
    statusRejected: 'Rad etilgan',
    approve: 'Tasdiqlash',
    reject: 'Rad etish',
    approveRequestTitle: "So'rovni tasdiqlash",
    approveRequestMessage: "Ushbu so'rovni tasdiqlashga ishonchingiz komilmi? Foydalanuvchi hisobi yaratiladi va faollashtiriladi.",
    rejectRequestTitle: "So'rovni rad etish",
    rejectRequestMessage: "Ushbu so'rovni rad etishga ishonchingiz komilmi?",
    rejectReasonLabel: 'Rad etish sababi (ixtiyoriy)',
    rejectReasonPlaceholder: 'Sababni kiriting...',
    requestApproved: "So'rov muvaffaqiyatli tasdiqlandi",
    requestRejected: "So'rov rad etildi",
    viewDetails: "Batafsil ko'rish",
    requestDetailsTitle: "So'rov tafsilotlari",
    photo: 'Rasm',
    createdDate: 'Yuborilgan sana',
    reviewedAt: "Ko'rib chiqilgan sana",
    reviewedBy: "Ko'rib chiquvchi",
    notes: 'Izoh',
    noPhoto: "Rasm yo'q",

    // ── Enable/disable users ──
    enableAction: 'Faollashtirish',
    enableUserTitle: 'Foydalanuvchini faollashtirish',
    enableUserMessage: 'Ushbu foydalanuvchini faollashtirishga ishonchingiz komilmi?',
    userEnabled: 'Foydalanuvchi faollashtirildi',

    // ── Profile page redesign ──
    personalInformation: "Shaxsiy ma'lumotlar",
    personalInformationDesc: "Hisobingizning shaxsiy va filial ma'lumotlari",
    accountStatus: 'Hisob holati',
    registrationDate: "Ro'yxatdan o'tgan sana",
    lastLogin: 'Oxirgi kirish',
    never: 'Hech qachon',
    profilePhoto: 'Profil rasmi',
    profilePhotoDesc: "Hisobingiz uchun rasm yuklang yoki o'zgartiring",
    removePhotoConfirmTitle: 'Rasmni o\'chirish',
    removePhotoConfirmMessage: 'Profil rasmini o\'chirishga ishonchingiz komilmi?',
    photoUpdated: 'Rasm muvaffaqiyatli yangilandi',
    photoRemoved: "Rasm o'chirildi",
    passwordStrength: 'Parol mustahkamligi',
    passwordStrengthWeak: 'Zaif',
    passwordStrengthFair: "O'rtacha",
    passwordStrengthGood: 'Yaxshi',
    passwordStrengthStrong: 'Kuchli',

    // ── Branches ──
    branches: 'Filiallar',
    branchesSubtitle: "Tashkilot filiallarini boshqarish",
    branchName: 'Filial nomi',
    createBranch: 'Filial qo\'shish',
    editBranch: 'Filialni tahrirlash',
    searchBranchesPlaceholder: "Kod, nom yoki telefon bo'yicha qidiring",
    noBranchesYet: "Hali filiallar yo'q",
    noBranchesYetDesc: "Birinchi filialni qo'shish uchun yuqoridagi tugmani bosing",
    unableToLoadBranches: "Filiallarni yuklab bo'lmadi",
    branchCreated: 'Filial muvaffaqiyatli yaratildi',
    branchUpdated: 'Filial muvaffaqiyatli yangilandi',
    branchEnabled: 'Filial faollashtirildi',
    branchDisabled: 'Filial faolsizlantirildi',
    enableBranchTitle: 'Filialni faollashtirish',
    enableBranchMessage: 'Ushbu filialni faollashtirishga ishonchingiz komilmi?',
    disableBranchTitle: 'Filialni faolsizlantirish',
    disableBranchMessage: 'Ushbu filialni faolsizlantirishga ishonchingiz komilmi?',
    valBranchCodeRequired: 'Filial kodini kiriting',
    valBranchNameRequired: 'Filial nomini kiriting',

    // ── Products ──
    products: 'Mahsulotlar',
    productsSubtitle: "Mahsulotlar katalogini va zaxirasini boshqarish",
    createProduct: "Mahsulot qo'shish",
    editProduct: 'Mahsulotni tahrirlash',
    product: 'Mahsulot',
    category: 'Toifa',
    brand: 'Brend',
    model: 'Model',
    qrCode: 'QR kod',
    productScore: 'Ball',
    categoryReducer: 'Redyuktor',
    categoryCylinder: 'Tsilindr',
    categoryEcu: 'ECU (boshqaruv bloki)',
    categoryInjectorRail: 'Injektor relsi',
    categoryFillingValve: "To'ldirish klapani",
    categoryMultivalve: 'Multiklapan',
    categoryPressureSensor: 'Bosim sensori',
    categoryFilter: 'Filtr',
    categoryOther: 'Boshqa',
    allCategories: 'Barcha toifalar',
    searchProductsPlaceholder: 'Brend, model, seriya yoki QR kod bo\'yicha qidiring',
    noProductsYet: "Hali mahsulotlar yo'q",
    noProductsYetDesc: "Birinchi mahsulotni qo'shish uchun yuqoridagi tugmani bosing",
    noProductsYetSyncDesc: "EasyGas katalogidan olish uchun \"EasyGas katalogini sinxronlash\" tugmasini bosing",
    noProductsMatch: 'Hech narsa topilmadi',
    noProductsMatchDesc: "Qidiruv yoki filtrlarni o'zgartirib ko'ring",
    unableToLoadProducts: "Mahsulotlarni yuklab bo'lmadi",
    productCreated: 'Mahsulot muvaffaqiyatli yaratildi',
    productUpdated: 'Mahsulot muvaffaqiyatli yangilandi',
    productDeleted: "Mahsulot o'chirildi",
    productActivatedToast: 'Mahsulot faollashtirildi',
    productDeactivatedToast: 'Mahsulot faolsizlantirildi',
    activateAction: 'Faollashtirish',
    deactivateAction: 'Faolsizlantirish',
    activateProductTitle: 'Mahsulotni faollashtirish',
    activateProductMessage: 'Ushbu mahsulotni faollashtirishga ishonchingiz komilmi? U qidiruvda qayta ko\'rinadi.',
    deactivateProductTitle: 'Mahsulotni faolsizlantirish',
    deactivateProductMessage: 'Ushbu mahsulotni faolsizlantirishga ishonchingiz komilmi? U endi qidiruvda ko\'rinmaydi.',
    deleteProductTitle: "Mahsulotni o'chirish",
    deleteProductMessage: "Ushbu mahsulotni o'chirishga ishonchingiz komilmi? Bu amalni bekor qilib bo'lmaydi.",
    productInStock: 'Omborda',
    productInstalled: "O'rnatilgan",
    productRetired: 'Chiqarilgan',

    // ── Brands ──
    brands: 'Brendlar',
    brandsSubtitle: 'Mahsulot brendlari katalogini boshqarish',
    createBrand: "Brend qo'shish",
    editBrand: 'Brendni tahrirlash',
    brandFullName: "To'liq nomi",
    country: 'Davlat',
    logoUrl: 'Logotip URL',
    searchBrandsPlaceholder: 'Brend nomi bo\'yicha qidiring',
    noBrandsYet: "Hali brendlar yo'q",
    noBrandsYetDesc: "Birinchi brendni qo'shish uchun yuqoridagi tugmani bosing",
    noBrandsYetSyncDesc: "EasyGas katalogidan olish uchun \"EasyGas katalogini sinxronlash\" tugmasini bosing",
    noBrandsMatch: 'Hech narsa topilmadi',
    noBrandsMatchDesc: "Qidiruvni o'zgartirib ko'ring",
    unableToLoadBrands: "Brendlarni yuklab bo'lmadi",
    brandCreated: 'Brend muvaffaqiyatli yaratildi',
    brandUpdated: 'Brend muvaffaqiyatli yangilandi',
    brandDeleted: "Brend o'chirildi",
    brandActivatedToast: 'Brend faollashtirildi',
    brandDeactivatedToast: 'Brend faolsizlantirildi',
    activateBrandTitle: 'Brendni faollashtirish',
    activateBrandMessage: 'Ushbu brendni faollashtirishga ishonchingiz komilmi? U mahsulot shaklida qayta ko\'rinadi.',
    deactivateBrandTitle: 'Brendni faolsizlantirish',
    deactivateBrandMessage: 'Ushbu brendni faolsizlantirishga ishonchingiz komilmi? U endi mahsulot shaklida ko\'rinmaydi.',
    deleteBrandTitle: "Brendni o'chirish",
    deleteBrandMessage: "Ushbu brendni o'chirishga ishonchingiz komilmi? Bu amalni bekor qilib bo'lmaydi.",
    brandInUseError: 'Ushbu brend mahsulotlarda ishlatilmoqda va o\'chirilmaydi — uni faolsizlantiring',
    valBrandNameRequired: 'Brend nomini kiriting',

    // ── Cars ──
    cars: 'Avtomobillar',
    carsSubtitle: 'Avtomobil modellari katalogini boshqarish',
    createCar: "Avtomobil qo'shish",
    editCar: 'Avtomobilni tahrirlash',
    searchCarsPlaceholder: 'Marka yoki model bo\'yicha qidiring',
    noCarsYet: "Hali avtomobillar yo'q",
    noCarsYetDesc: "Birinchi avtomobilni qo'shish uchun yuqoridagi tugmani bosing",
    noCarsYetSyncDesc: "EasyGas katalogidan olish uchun \"EasyGas katalogini sinxronlash\" tugmasini bosing",
    noCarsMatch: 'Hech narsa topilmadi',
    noCarsMatchDesc: "Qidiruvni o'zgartirib ko'ring",
    unableToLoadCars: "Avtomobillarni yuklab bo'lmadi",
    carCreated: 'Avtomobil muvaffaqiyatli yaratildi',
    carUpdated: 'Avtomobil muvaffaqiyatli yangilandi',
    carDeleted: "Avtomobil o'chirildi",
    carActivatedToast: 'Avtomobil faollashtirildi',
    carDeactivatedToast: 'Avtomobil faolsizlantirildi',
    activateCarTitle: 'Avtomobilni faollashtirish',
    activateCarMessage: 'Ushbu avtomobilni faollashtirishga ishonchingiz komilmi? U qidiruvda qayta ko\'rinadi.',
    deactivateCarTitle: 'Avtomobilni faolsizlantirish',
    deactivateCarMessage: 'Ushbu avtomobilni faolsizlantirishga ishonchingiz komilmi? U endi qidiruvda ko\'rinmaydi.',
    deleteCarTitle: "Avtomobilni o'chirish",
    deleteCarMessage: "Ushbu avtomobilni o'chirishga ishonchingiz komilmi? Bu amalni bekor qilib bo'lmaydi.",
    carInUseError: 'Ushbu avtomobil kafolatlarda ishlatilmoqda va o\'chirilmaydi — uni faolsizlantiring',
    valCarBrandRequired: 'Avtomobil markasini kiriting',
    valCarModelRequired: 'Avtomobil modelini kiriting',

    // ── EasyGas catalog sync (Products/Brands/Cars are read-only, synced from EasyGas) ──
    catalogSync: 'EasyGas sinxronizatsiyasi',
    catalogSyncSubtitle: 'Mahsulotlar, brendlar va avtomobillarni EasyGas bilan sinxronlash',
    catalogReadOnlyNotice: 'Bu katalog EasyGas orqali sinxronlanadi va qo\'lda tahrirlanmaydi. Sinxronlash uchun:',
    syncCatalogButton: 'EasyGas katalogini sinxronlash',
    syncing: 'Sinxronlanmoqda...',
    syncRunning: 'Ishlamoqda...',
    lastSyncLabel: 'Oxirgi sinxronlash',
    syncNeverRun: 'Hali sinxronlanmagan',
    syncStatusSuccess: 'Muvaffaqiyatli',
    syncStatusFailed: 'Muvaffaqiyatsiz',
    syncStatusRunning: 'Ishlamoqda',
    syncDurationLabel: 'Davomiyligi',
    syncInserted: 'Qo\'shildi',
    syncUpdated: 'Yangilandi',
    syncSkipped: 'O\'tkazib yuborildi',
    syncFailed: 'Xato',
    syncProductsUpdated: 'Mahsulotlar yangilandi',
    syncBrandsUpdated: 'Brendlar yangilandi',
    syncCarsUpdated: 'Avtomobillar yangilandi',
    syncReasonNetwork: 'EasyGas serveriga ulanib bo\'lmadi yoki so\'rov vaqti tugadi',
    syncReasonHttpError: 'EasyGas xato qaytardi:',
    syncReasonUnknown: 'Noma\'lum xato',

    // ── Inventory ──
    inventory: 'Ombor',
    inventorySubtitle: "Mahsulotlar uchun jismoniy zaxirani (shtrix-kodlar) boshqarish",
    inventoryImportAction: 'CSV import qilish',
    inventorySearchPlaceholder: 'Shtrix-kod bo\'yicha qidiring',
    inventoryBarcode: 'Shtrix-kod',
    inventoryCsvFile: 'CSV fayl',
    inventoryStatusInStock: 'Mavjud',
    inventoryStatusReserved: 'Band qilingan',
    inventoryStatusInstalled: "O'rnatilgan",
    inventoryStatusReturned: 'Qaytarilgan',
    inventoryStatusDamaged: 'Shikastlangan',
    inventoryStatusLost: "Yo'qolgan",
    noInventoryYet: "Hali ombor yozuvlari yo'q",
    noInventoryYetDesc: "Birinchi shtrix-kodlarni import qilish uchun yuqoridagi tugmani bosing",
    noInventoryMatch: 'Hech narsa topilmadi',
    noInventoryMatchDesc: "Qidiruv yoki filtrlarni o'zgartirib ko'ring",
    unableToLoadInventory: "Omborni yuklab bo'lmadi",
    inventoryImported: 'Import qilindi',
    inventorySkipped: "O'tkazib yuborildi",
    inventoryDuplicates: 'Takrorlanganlar',
    inventoryErrors: 'Xatolar',
    inventoryImportSuccess: 'Import muvaffaqiyatli yakunlandi',

    // ── Installer points ──
    points: 'Ballar',
    myPoints: 'Mening ballarim',
    myPointsSubtitle: "O'rnatilgan har bir jihoz uchun qo'lga kiritilgan va qaytarilgan ballar tarixi",
    installerPoints: "O'rnatuvchilar ballari",
    installerPointsSubtitle: "Har bir o'rnatuvchining ball tarixini ko'rish va qo'lda tuzatish kiritish",
    pointsConfig: 'Ball sozlamalari',
    pointsConfigSubtitle: "Har bir mahsulot uchun ball qiymatini belgilang — o'zgarish faqat kelajakdagi kafolatlarga ta'sir qiladi",
    totalPoints: 'Jami ballar',
    pointsHistory: 'Ballar tarixi',
    noPointsYet: "Hali ball yozuvlari yo'q",
    noPointsYetDesc: "Kafolat topshirilganda ballar shu yerda ko'rinadi",
    unableToLoadPoints: "Ballarni yuklab bo'lmadi",
    pointValueLabel: 'Ball qiymati',
    savePointValue: 'Saqlash',
    pointValueUpdated: 'Ball qiymati yangilandi',
    selectInstallerPlaceholder: "O'rnatuvchini tanlang",
    searchInstallerPlaceholder: "O'rnatuvchi bo'yicha qidiring",
    manualAdjustment: "Qo'lda tuzatish",
    createAdjustment: 'Tuzatish kiritish',
    adjustmentType: 'Tur',
    adjustmentPoints: 'Ball miqdori',
    adjustmentReason: 'Sabab',
    adjustmentReasonPlaceholder: 'Nima uchun bu tuzatish kiritilyapti?',
    bonusLabel: 'Bonus',
    penaltyLabel: 'Jarima',
    adjustmentLabel: 'Tuzatish',
    adjustmentCreated: 'Tuzatish muvaffaqiyatli kiritildi',
    pointsTypeWarrantyAward: "Kafolat uchun ball",
    pointsTypeWarrantyReversal: 'Ball qaytarildi',
    pointsTypeManualAdjustment: "Qo'lda tuzatish",
    pointsTypeManualBonus: 'Bonus',
    pointsTypeManualPenalty: 'Jarima',
    pointsDateColumn: 'Sana',
    pointsReasonColumn: 'Sabab',
    pointsAmountColumn: 'Ball',
    pointsTypeColumn: 'Tur',
    selectAnInstaller: "Ballar tarixini ko'rish uchun o'rnatuvchini tanlang",
    superAdminOnlyHint: "Faqat Super Admin ball qiymatlarini o'zgartirishi va tuzatish kirita oladi",
    typedCylinderPointValue: 'Katalogsiz ballon',
    typedCylinderPointValueHint: "Katalogdan tanlanmagan, qo'lda kiritilgan ballon uchun ball qiymati",
    typedCylinderLabel: 'Katalogsiz ballon',

    // ── Phase 4: inventory filters, manual operations ──
    inventoryStatusMerged: 'Birlashtirilgan',
    filterByInstaller: "O'rnatuvchi",
    filterByWarehouse: "Ombor",
    filterByImportBatch: "Import partiyasi",
    installedFromLabel: "O'rnatilgan sanadan",
    installedToLabel: "O'rnatilgan sanagacha",
    claimedFromLabel: "Band qilingan sanadan",
    claimedToLabel: "Band qilingan sanagacha",
    advancedFilters: "Qo'shimcha filtrlar",
    warehouseLabel: 'Ombor',
    allWarehouses: 'Barcha omborlar',
    unassignedWarehouse: 'Tayinlanmagan',
    manualOperations: "Qo'lda amallar",
    changeStatusAction: "Holatni o'zgartirish",
    transferBranchAction: "Omborga ko'chirish",
    correctBarcodeAction: 'Shtrix-kodni tuzatish',
    mergeDuplicateAction: 'Nusxani birlashtirish',
    newStatusLabel: 'Yangi holat',
    newBarcodeLabel: 'Yangi shtrix-kod',
    canonicalItemLabel: 'Asosiy element (shtrix-kod)',
    reasonLabel: 'Sabab',
    reasonPlaceholderGeneric: 'Nima uchun bu amal bajarilyapti?',
    operationSuccess: 'Amal muvaffaqiyatli bajarildi',
    confirmMergeTitle: 'Nusxani birlashtirishni tasdiqlang',
    confirmMergeMessage: "Bu element asosiy elementga birlashtiriladi va bu amalni qaytarib bo'lmaydi. Davom etasizmi?",

    // ── Phase 4: reports dashboard ──
    reportsDashboard: 'Hisobotlar paneli',
    totalProductsLabel: 'Jami mahsulotlar',
    totalInventoryLabel: 'Jami zaxira',
    installedProductsLabel: "O'rnatilgan mahsulotlar",
    availableInventoryLabel: 'Mavjud zaxira',
    damagedInventoryLabel: 'Shikastlangan zaxira',
    lostInventoryLabel: "Yo'qolgan zaxira",
    returnedInventoryLabel: 'Qaytarilgan zaxira',
    importedTodayLabel: 'Bugun import qilindi',
    importedThisMonthLabel: 'Shu oy import qilindi',
    topInstalledProductsLabel: "Eng ko'p o'rnatilgan mahsulotlar",
    topWarehousesLabel: 'Eng yirik omborlar',
    pointsLeaderboardLabel: 'Ballar reytingi',
    recentImportsLabel: "So'nggi importlar",
    recentWarrantyActivityLabel: "So'nggi kafolat faoliyati",
    recentInventoryActivityLabel: "So'nggi ombor faoliyati",

    // ── Phase 4: statistics pages ──
    installerStatistics: "O'rnatuvchi statistikasi",
    productStatistics: 'Mahsulot statistikasi',
    warehouseStatistics: 'Ombor statistikasi',
    myStatistics: 'Mening statistikam',
    monthlyPoints: 'Oylik ballar',
    lifetimePoints: 'Umumiy ballar',
    totalClaimedInventoryLabel: 'Jami band qilingan zaxira',
    activityGraphLabel: 'Faollik grafigi',
    importedQuantityLabel: 'Import qilingan miqdor',
    installedQuantityLabel: "O'rnatilgan miqdor",
    remainingStockLabel: 'Qolgan zaxira',
    failureRateLabel: 'Nosozlik darajasi',
    returnRateLabel: 'Qaytarish darajasi',
    topBranchesLabel: 'Eng faol filiallar',
    currentStockLabel: 'Joriy zaxira',
    installedStockLabel: "O'rnatilgan zaxira",
    reservedStockLabel: 'Band qilingan zaxira',
    movementHistoryLabel: 'Harakat tarixi',
    selectProductPlaceholder: 'Mahsulotni tanlang',
    selectWarehousePlaceholder: 'Omborni tanlang',
    exportCsvAction: 'CSV eksport qilish',
    exportingCsv: 'Eksport qilinmoqda...',

    valCategoryRequired: 'Toifani tanlang',
    valBrandRequired: 'Brendni tanlang',
    valSerialRequired: 'Seriya raqamini kiriting',
    valScoreInvalid: "Ball 0 dan katta yoki teng butun son bo'lishi kerak",
    productCodeLabel: 'Seriya raqami yoki QR kod',
    productCodePlaceholder: "Kodni kiriting yoki skanerlang",
    addProduct: "Qo'shish",
    productAlreadyAdded: "Bu mahsulot allaqachon qo'shilgan",
    removeProduct: "Mahsulotni olib tashlash",
    legacyEquipmentTitle: "Ilgari qayd etilgan uskunalar",
    legacyEquipmentDesc: "Mahsulot kuzatuvidan oldin kiritilgan (faqat o'qish uchun)",
    valProductsRequired: 'Kamida bitta mahsulot qo\'shing',

    // ── Reports ──
    reports: 'Hisobotlar',
    reportsSubtitle: "O'rnatuvchilar reytingi, filiallar va mahsulotlar bo'yicha hisobotlar",
    unableToLoadReports: "Hisobotlarni yuklab bo'lmadi",
    totalWarrantiesInPeriod: 'Davr uchun kafolatlar',
    totalEquipmentInstalled: "Jami o'rnatilgan jihozlar",
    topInstallers: "Yetakchi o'rnatuvchilar",
    branchRanking: 'Filiallar reytingi',
    productsInstalledTitle: "O'rnatilgan mahsulotlar",
    monthlyActivityTitle: 'Oylik faollik dinamikasi',
    warrantyCount: 'Kafolatlar soni',
    noReportDataYet: "Hali ma'lumot yo'q",
    noReportDataYetDesc: "Kafolat formalari va mahsulotlar qo'shilgach, bu yerda ko'rinadi",
  },
  ru: {
    login: 'Вход',
    logout: 'Выход',
    profile: 'Профиль',
    dashboard: 'Главная',
    welcome: 'Добро пожаловать',
    username: 'Имя пользователя',
    password: 'Пароль',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтвердить пароль',
    changePassword: 'Изменить пароль',
    loginFailed: 'Ошибка входа',
    passwordChanged: 'Пароль изменен',
    warrantyForm: 'Гарантийная форма',
    submitForm: 'Отправить',
    formSubmitted: 'Успешно отправлено',
    myProfile: 'Мой профиль',
    users: 'Пользователи',
    manageUsers: 'Управление пользователями',
    createUser: 'Создать пользователя',
    editUser: 'Редактировать',
    deleteUser: 'Удалить',
    warrantyForms: 'Гарантийные формы',
    searchForms: 'Поиск',
    exportExcel: 'Экспорт Excel',
    totalForms: 'Всего форм',
    totalEmployees: 'Всего сотрудников',
    warrantyInfo: 'Информация о гарантии',
    vehicleInfo: 'Информация об автомобиле',
    equipmentInfo: 'Информация об оборудовании',
    region: 'Область',
    city: 'Город',
    district: 'Район',
    organizationName: 'Название организации',
    organizationPhone: 'Телефон организации',
    installerName: 'Имя установщика',
    installerPhone: 'Телефон установщика',
    warrantyBookNumber: 'Номер гарантии',
    warrantyNumberPendingSync: 'Будет присвоен автоматически после отправки',
    valYearRange: 'Год выпуска должен быть не ранее 1950 и не в будущем',
    valMileageRange: 'Некорректное значение пробега',
    valInstallationDateRange: 'Дата установки должна быть не ранее 2015 года и не в будущем',
    installationDate: 'Дата установки',
    vehicleBrand: 'Марка автомобиля',
    vehicleModel: 'Модель',
    vehicleName: 'Автомобиль',
    vehicleNamePlaceholder: 'Например: Chevrolet Cobalt',
    productionYear: 'Год',
    plateNumber: 'Гос. номер',
    plateNumberOptionalHint: 'Если ещё нет номера, оставьте пустым',
    vinNumber: 'VIN',
    engineVolume: 'Объем двигателя',
    enginePower: 'Мощность двигателя',
    mileage: 'Пробег',
    ownerName: 'Имя владельца',
    ownerPhone: 'Телефон владельца',
    reducer: 'Редуктор',
    cylinder: 'Цилиндр',
    controller: 'Контроллер STAG',
    injectorRail: 'Инжекторная рейка',
    fuelType: 'Тип топлива',
    manufacturer: 'Производитель',
    serialNumber: 'Серийный номер',
    serialVinNumber: 'Серийный/VIN номер',
    barcodeScanOrType: 'Отсканируйте или введите штрих-код',
    selectProductFirst: 'Сначала выберите продукт',
    productSearchPlaceholder: 'Введите название продукта (например: STAG)',
    selectBrandFirst: 'Сначала выберите бренд',
    selectOption: 'Выберите',
    loadingResults: 'Поиск...',
    noResultsFound: 'Ничего не найдено',
    vehicleNotInCatalogHint: 'Нет в списке — введённый текст всё равно будет сохранён',
    valProductRequired: 'Выберите продукт',
    // ── Manual Verification — HISTORICAL admin review UI only (the active
    // installer workflow was disabled 2026-08-26 and its keys removed;
    // these remain for viewing/resolving old records) ──
    sellerName: 'Имя продавца',
    sellerPhone: 'Телефон продавца',
    verificationComment: 'Комментарий',
    verificationPhotoOptional: 'Фото (необязательно)',
    verificationStatusColumn: 'Статус проверки',
    verificationFilterAll: 'Все проверки',
    verificationStatusPending: 'На рассмотрении',
    verificationStatusApproved: 'Одобрено',
    verificationStatusRejected: 'Отклонено',
    approveVerificationTitle: 'Подтвердить ручную проверку',
    approveVerificationMessage: 'Вы уверены, что хотите подтвердить ручную проверку этого оборудования? Баллы будут начислены немедленно.',
    verificationApproved: 'Ручная проверка подтверждена',
    verificationRejected: 'Ручная проверка отклонена',
    rejectVerificationTitle: 'Отклонить ручную проверку',
    rejectVerificationMessage: 'Вы уверены, что хотите отклонить ручную проверку этого оборудования? Гарантия будет помечена как отклонённая.',
    // Warranty status workflow — the warranty form's own lifecycle,
    // separate from verification* keys above (Manual Verification).
    warrantyStatusColumn: 'Статус гарантии',
    warrantyStatusPending: 'На рассмотрении',
    warrantyStatusSuccessful: 'Успешно',
    warrantyStatusRejected: 'Отклонено',
    approveWarrantyTitle: 'Подтвердить гарантию',
    approveWarrantyMessage: 'Вы уверены, что хотите подтвердить эту гарантию? После подтверждения она будет автоматически отправлена в EasyGas.',
    rejectWarrantyTitle: 'Отклонить гарантию',
    rejectWarrantyMessage: 'Вы уверены, что хотите отклонить эту гарантию? Отклонённые гарантии никогда не отправляются в EasyGas.',
    warrantyApproved: 'Гарантия подтверждена',
    warrantyRejected: 'Гарантия отклонена',
    viewEasyGasWarranty: 'Посмотреть гарантию EasyGas',
    viewEasyGasWarrantyShort: 'EasyGas',
    easyGasSyncFailed: 'Ошибка отправки в EasyGas',
    // EasyGas claim_url QR presentation
    easyGasWarrantyTitle: 'Гарантия EasyGas',
    scanWarrantyQrHint: 'Отсканируйте QR-код камерой телефона, чтобы открыть гарантию',
    openWarrantyLink: 'Открыть ссылку',
    easyGasSyncFailedInstaller: 'Произошла ошибка при создании гарантии EasyGas',
    easyGasSyncErrorLabel: 'Детали ошибки',
    // ── Customer lookup (Поиск клиента, Beta-1) ──
    customerLookup: 'Поиск клиента',
    customerLookupDesc: 'Найдите установленное оборудование и гарантии по номеру телефона клиента',
    searchAction: 'Поиск',
    noCustomerFound: 'Клиент не найден',
    noCustomerFoundDesc: 'По этому номеру гарантий не найдено. Проверьте номер и попробуйте снова.',
    lookupFailed: 'Ошибка при поиске',
    installedEquipment: 'Установленное оборудование',
    installerLabel: 'Мастер',
    branchLabel: 'Филиал',
    serialLabel: 'Серия',
    notProvided: 'Не указано',
    // ── Searchable branch selector (Beta-1) ──
    branchSearchPlaceholder: 'Поиск по коду или названию филиала',
    branchSearchOptionalPlaceholder: 'Филиал (необязательно) — поиск по коду или названию',
    noBranchesFound: 'Филиал не найден',
    // ── Optional cylinder (Beta-3) ──
    optionalLabel: 'Необязательно',
    addCylinderAction: 'Добавить баллон',
    removeCylinderAction: 'Удалить баллон',
    cylinderNotAdded: 'Баллон не указан',
    typedCylinderInfo: 'Баллон, введённый вручную',
    // ── Branch business-group classification (Beta-2) ──
    branchTypeLabel: 'Тип сервиса',
    branchTypeFilterAll: 'Все',
    branchTypeEasyGas: 'EasyGas',
    branchTypeStagService: 'STAG Service',
    branchTypeOtherService: 'Другие сервисы',
    branchTypeUnclassified: 'Не назначено',
    usernameFormatHelperTitle: 'Формат username: prefix_imya_region_filial',
    usernamePrefixLegend: 'eg = EasyGas · st = STAG Service · bs = Другие сервисы',
    usernameBranchMismatchHint: 'Код филиала в username не совпадает с выбранным филиалом',
    // ── Beta-2.1: registration approval + explicit reclassification ──
    applicantUsernameLabel: 'Username заявителя',
    approveRequestFinalUsername: 'Финальный managed username',
    approveRequestUsernameHint: 'Собственный username заявителя не становится финальным аккаунтом — администратор вводит managed username.',
    reclassifyBranchAction: 'Исправить тип сервиса',
    reclassifyBranchWarning: 'Это исключительная корректирующая операция: тип сервиса филиала обычно устанавливается при онбординге сотрудников. Используйте только для исправления неверно установленного типа.',
    currentTypeLabel: 'Текущий тип',
    newTypeLabel: 'Новый тип',
    branchReclassified: 'Тип сервиса филиала обновлён',
    easyGasInconsistentState: 'Несогласованное состояние EasyGas: синхронизация помечена как успешная, но ссылка на гарантию отсутствует.',
    // EasyGas /verify lookup (admin catalog sync page) — requires one of
    // phone/vin/serial, entered explicitly by the admin
    verifyEasyGasTitle: 'Проверка EasyGas',
    verifyEasyGasHint: 'Для проверки введите номер телефона, VIN или серийный номер',
    verifyTypePhone: 'Номер телефона',
    verifyTypeVin: 'VIN',
    verifyTypeSerial: 'Серийный номер',
    verifyRunButton: 'Проверить',
    verifyOkResult: 'Запрос выполнен — ответ ниже',
    verifyFailedResult: 'Проверка не удалась',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    view: 'Просмотр',
    clear: 'Очистить',
    loading: 'Загрузка...',
    error: 'Ошибка',
    success: 'Успех',
    search: 'Поиск',
    filter: 'Фильтр',
    employee: 'Сотрудник',
    required: 'Обязательно',
    date: 'Дата',
    phone: 'Телефон',
    actions: 'Действия',
    exportData: 'Экспорт данных',
    timePeriod: 'Период времени',
    loginTitle: "Система управления гарантиями",
    empAlert: "Заполните форму гарантии, указав данные о вашей установке.",
    empProfile: "Управление настройками учетной записи",
    empAccount: "Информация об учетной записи",
    empAccountDetails: "Основные данные вашей учетной записи",
    myWarrantyHistory: "Моя история гарантий",
    myWarrantyHistoryDesc: "Мои отправленные гарантийные формы",
    noWarrantyHistory: "История гарантий пуста",
    noWarrantyHistoryDesc: "Вы ещё не отправили ни одной гарантийной формы",
    editWarranty: "Редактировать",
    editWarrantyTitle: "Редактировать гарантию",
    saveChanges: "Сохранить изменения",
    editExpired: "Прошло 24 часа, редактирование недоступно",
    dashboardSubtitle: "Добро пожаловать! Обзор системы и последняя активность.",
    thisWeek: 'На этой неделе',
    topBranch: 'Лидирующий филиал',
    submissionsTrend: 'Динамика за последние 14 дней',
    fuelTypeBreakdown: 'Распределение по типу топлива',
    topOrganizations: 'Активные организации',
    recentSubmissions: 'Последние гарантии',
    noRecentSubmissions: 'Гарантии ещё не поданы',
    noRecentSubmissionsDesc: 'Здесь появятся формы, отправленные сотрудниками',
    viewAll: 'Смотреть все',
    quickActions: 'Быстрые действия',
    qaViewForms: 'Просмотреть гарантийные формы',
    qaManageUsers: 'Управление пользователями',
    qaExportReport: 'Экспортировать отчёт',
    notifications: 'Уведомления',
    noNotifications: 'Новых уведомлений нет',
    noNotificationsDesc: 'Всё под контролем. Новые события появятся здесь.',
    systemStatus: 'Состояние системы',
    apiOnline: 'API работает',
    databaseConnected: 'База данных подключена',
    lastSynced: 'Последнее обновление',
    refresh: 'Обновить',
    vehicle: 'Автомобиль',
    owner: 'Владелец',
    branch: 'Филиал',
    submissionsUnit: 'шт.',
    navWarrantyHistory: 'История гарантий',
    searchPlaceholder: 'Поиск страницы...',
    searchNoResults: 'Ничего не найдено',
    collapseSidebar: 'Свернуть панель',
    expandSidebar: 'Развернуть панель',
    myAccount: 'Мой аккаунт',
    warrantyDetailsTitle: 'Детали гарантии',
    searchFormsPlaceholder: 'Поиск по номеру, владельцу или сотруднику',
    searchHistoryPlaceholder: 'Поиск по номеру или владельцу',
    perPage: 'на странице',
    allForms: 'Все формы',
    adminWarrantySubtitle: 'Управление и просмотр всех гарантийных форм',
    filteredByInstallerLabel: 'Отфильтровано по установщику',
    clearInstallerFilter: 'Показать все гарантии',
    viewInstallerWarranties: 'Посмотреть гарантии',
    noFormsFound: 'Гарантии не найдены',
    noFormsFoundDesc: 'Попробуйте изменить параметры поиска',
    deleteFormTitle: 'Удалить форму',
    deleteFormMessage: 'Вы уверены, что хотите удалить эту гарантийную форму? Это действие нельзя отменить.',
    formDeleted: 'Форма успешно удалена',
    formUpdated: 'Гарантийная форма успешно обновлена!',
    fillRequiredFields: 'Заполните все обязательные поля',
    editExpiresIn: 'Осталось на редактирование',
    hoursShort: 'ч',
    successFormDesc: 'Ваша гарантийная форма успешно принята',
    sectionWarranty: 'Гарантийная информация',
    sectionVehicle: 'Информация об автомобиле',
    sectionOwner: 'Информация о владельце',
    sectionEquipment: 'Информация об оборудовании',
    scanCertificate: 'Сканировать паспорт',
    sectionComplete: 'Все поля заполнены',
    selectPlaceholder: 'Выберите...',
    fullName: 'Полное имя',
    signIn: 'Вход',
    signingIn: 'Вход...',
    signUp: 'Регистрация',
    creatingAccount: 'Создание...',
    createAccount: 'Создать аккаунт',
    dontHaveAccount: 'Нет аккаунта?',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    usernamePlaceholder: 'Введите имя пользователя',
    passwordPlaceholder: 'Введите пароль',
    chooseUsernamePlaceholder: 'Придумайте имя пользователя',
    atLeast6CharsPlaceholder: 'Минимум 6 символов',
    repeatPasswordPlaceholder: 'Повторите пароль',
    phoneOptional: 'Телефон (необязательно)',
    fullNamePlaceholder: 'Введите полное имя',
    last7Days: 'Последние 7 дней',
    last30Days: 'Последние 30 дней',
    last3Months: 'Последние 3 месяца',
    last6Months: 'Последние 6 месяцев',
    last1Year: 'Последний год',
    allData: 'Все данные',
    security: 'Настройки безопасности',
    securityDesc: 'Управляйте паролем и безопасностью',
    exportMyData: 'Экспортировать мои данные',
    exportMyDataDesc: 'Скачайте мои гарантийные формы в формате Excel',
    downloadExcel: 'Скачать Excel',
    exportingLabel: 'Экспорт...',
    branchCode: 'Код филиала',
    active: 'Активен',
    status: 'Статус',
    exportWarrantyDataDesc: 'Скачайте гарантийные формы с необязательной фильтрацией по дате',
    exportToExcel: 'Экспорт в Excel',
    inactive: 'Неактивен',
    usersSubtitle: 'Управление пользователями системы и правами доступа',
    searchUsersPlaceholder: 'Поиск по имени, логину или филиалу',
    allStatuses: 'Все статусы',
    noEmployeesYet: 'Пока нет сотрудников',
    noEmployeesYetDesc: 'Нажмите кнопку выше, чтобы добавить первого сотрудника',
    noUsersMatch: 'Никого не найдено',
    noUsersMatchDesc: 'Попробуйте изменить поиск или фильтры',
    resetPasswordAction: 'Сбросить пароль',
    disableAction: 'Деактивировать',
    disableUserTitle: 'Деактивировать пользователя',
    disableUserMessage: 'Вы уверены, что хотите деактивировать этого пользователя?',
    resetPasswordConfirmTitle: 'Сброс пароля',
    resetPasswordConfirmMessage: 'Будет создан новый временный пароль. Пользователю нужно будет изменить его при следующем входе.',
    userCreated: 'Пользователь успешно создан',
    userUpdated: 'Пользователь успешно обновлён',
    userDisabled: 'Пользователь деактивирован',
    newPasswordTitle: 'Создан новый пароль',
    newPasswordDesc: 'Передайте этот пароль сотруднику безопасным способом. Повторно его увидеть будет нельзя.',
    copyToClipboard: 'Копировать',
    copied: 'Скопировано!',
    done: 'Готово',
    sessionExpiredMessage: 'Сессия истекла. Пожалуйста, войдите снова.',

    // ── Validation messages (Zod factory schemas) ──
    valFirstNameRequired: 'Введите имя',
    valLastNameRequired: 'Введите фамилию',
    valFullNameRequired: 'Введите полное имя',
    valRegionRequired: 'Выберите область',
    valDistrictRequired: 'Выберите район',
    valBranchRequired: 'Выберите филиал',
    valPhoneInvalid: 'Неверный номер телефона (например: +998901234567)',
    valUsernameRequired: 'Введите имя пользователя',
    valUsernameMinLength: 'Имя пользователя должно содержать минимум 3 символа',
    valPasswordRequired: 'Введите пароль',
    valPasswordMinLength: 'Пароль должен содержать минимум 6 символов',
    valConfirmPasswordRequired: 'Подтвердите пароль',
    valPasswordsMismatch: 'Пароли не совпадают',
    valCurrentPasswordRequired: 'Введите текущий пароль',
    valPhotoRequired: 'Необходимо загрузить фото',
    valPhotoInvalidType: 'Неверный формат файла. Только JPG, PNG или WEBP',
    valPhotoTooLarge: 'Размер файла не должен превышать 5 МБ',
    fieldRequired: 'Это поле обязательно для заполнения',

    // ── Generic UI ──
    admin: 'Администратор',
    unableToLoadData: 'Не удалось загрузить данные',
    unableToLoadProfile: 'Не удалось загрузить профиль',
    unableToLoadUsers: 'Не удалось загрузить пользователей',
    unableToLoadForms: 'Не удалось загрузить гарантийные формы',
    unableToLoadHistory: 'Не удалось загрузить историю',
    unableToLoadDashboard: 'Не удалось загрузить панель управления',
    unableToLoadRequests: 'Не удалось загрузить заявки',
    tryAgain: 'Повторить попытку',
    close: 'Закрыть',
    confirm: 'Подтвердить',
    somethingWentWrong: 'Что-то пошло не так',
    unexpectedErrorOnPage: 'На этой странице произошла непредвиденная ошибка.',
    home: 'Главная',
    refreshPage: 'Обновить страницу',
    breadcrumbAria: 'Навигационная цепочка',
    hidePassword: 'Скрыть пароль',
    showPassword: 'Показать пароль',
    previousPage: 'Предыдущая страница',
    nextPage: 'Следующая страница',
    closeMenu: 'Закрыть меню',
    openMenu: 'Открыть меню',
    errorSubmittingForm: 'Ошибка при отправке формы',

    // ── Registration form ──
    firstName: 'Имя',
    lastName: 'Фамилия',
    firstNamePlaceholder: 'Введите имя',
    lastNamePlaceholder: 'Введите фамилию',
    personalPhoto: 'Личное фото',
    uploadPhoto: 'Загрузить фото',
    removePhoto: 'Удалить фото',
    changePhoto: 'Изменить фото',
    submitRequest: 'Отправить заявку',
    submittingRequest: 'Отправка...',
    registrationPendingTitle: 'Заявка отправлена',
    registrationPendingMessage: 'Ваша заявка успешно отправлена.\nПосле проверки администратор свяжется с вами.',
    backToLogin: 'Вернуться на страницу входа',

    // ── Admin: Registration Requests ──
    registrationRequests: 'Заявки',
    registrationRequestsSubtitle: 'Просмотр и подтверждение заявок на регистрацию',
    searchRequestsPlaceholder: 'Поиск по имени, логину или филиалу',
    noRequestsYet: 'Заявок пока нет',
    noRequestsYetDesc: 'Новые заявки на регистрацию появятся здесь',
    noRequestsMatch: 'Ничего не найдено',
    noRequestsMatchDesc: 'Попробуйте изменить поиск или фильтры',
    statusPending: 'Ожидает',
    statusApproved: 'Одобрено',
    statusRejected: 'Отклонено',
    approve: 'Одобрить',
    reject: 'Отклонить',
    approveRequestTitle: 'Подтвердить заявку',
    approveRequestMessage: 'Вы уверены, что хотите подтвердить эту заявку? Будет создана и активирована учётная запись пользователя.',
    rejectRequestTitle: 'Отклонить заявку',
    rejectRequestMessage: 'Вы уверены, что хотите отклонить эту заявку?',
    rejectReasonLabel: 'Причина отклонения (необязательно)',
    rejectReasonPlaceholder: 'Введите причину...',
    requestApproved: 'Заявка успешно подтверждена',
    requestRejected: 'Заявка отклонена',
    viewDetails: 'Подробнее',
    requestDetailsTitle: 'Детали заявки',
    photo: 'Фото',
    createdDate: 'Дата подачи',
    reviewedAt: 'Дата рассмотрения',
    reviewedBy: 'Рассмотрел',
    notes: 'Примечание',
    noPhoto: 'Нет фото',

    // ── Enable/disable users ──
    enableAction: 'Активировать',
    enableUserTitle: 'Активировать пользователя',
    enableUserMessage: 'Вы уверены, что хотите активировать этого пользователя?',
    userEnabled: 'Пользователь активирован',

    // ── Profile page redesign ──
    personalInformation: 'Личная информация',
    personalInformationDesc: 'Личные данные и данные филиала вашей учётной записи',
    accountStatus: 'Статус аккаунта',
    registrationDate: 'Дата регистрации',
    lastLogin: 'Последний вход',
    never: 'Никогда',
    profilePhoto: 'Фото профиля',
    profilePhotoDesc: 'Загрузите или измените фото для своей учётной записи',
    removePhotoConfirmTitle: 'Удалить фото',
    removePhotoConfirmMessage: 'Вы уверены, что хотите удалить фото профиля?',
    photoUpdated: 'Фото успешно обновлено',
    photoRemoved: 'Фото удалено',
    passwordStrength: 'Надёжность пароля',
    passwordStrengthWeak: 'Слабый',
    passwordStrengthFair: 'Средний',
    passwordStrengthGood: 'Хороший',
    passwordStrengthStrong: 'Надёжный',

    // ── Branches ──
    branches: 'Филиалы',
    branchesSubtitle: 'Управление филиалами организации',
    branchName: 'Название филиала',
    createBranch: 'Добавить филиал',
    editBranch: 'Редактировать филиал',
    searchBranchesPlaceholder: 'Поиск по коду, названию или телефону',
    noBranchesYet: 'Филиалов пока нет',
    noBranchesYetDesc: 'Нажмите кнопку выше, чтобы добавить первый филиал',
    unableToLoadBranches: 'Не удалось загрузить филиалы',
    branchCreated: 'Филиал успешно создан',
    branchUpdated: 'Филиал успешно обновлён',
    branchEnabled: 'Филиал активирован',
    branchDisabled: 'Филиал деактивирован',
    enableBranchTitle: 'Активировать филиал',
    enableBranchMessage: 'Вы уверены, что хотите активировать этот филиал?',
    disableBranchTitle: 'Деактивировать филиал',
    disableBranchMessage: 'Вы уверены, что хотите деактивировать этот филиал?',
    valBranchCodeRequired: 'Введите код филиала',
    valBranchNameRequired: 'Введите название филиала',

    // ── Products ──
    products: 'Продукты',
    productsSubtitle: 'Управление каталогом и запасами продукции',
    createProduct: 'Добавить продукт',
    editProduct: 'Редактировать продукт',
    product: 'Продукт',
    category: 'Категория',
    brand: 'Бренд',
    model: 'Модель',
    qrCode: 'QR-код',
    productScore: 'Баллы',
    categoryReducer: 'Редуктор',
    categoryCylinder: 'Цилиндр',
    categoryEcu: 'ЭБУ (блок управления)',
    categoryInjectorRail: 'Инжекторная рейка',
    categoryFillingValve: 'Заправочный клапан',
    categoryMultivalve: 'Мультиклапан',
    categoryPressureSensor: 'Датчик давления',
    categoryFilter: 'Фильтр',
    categoryOther: 'Другое',
    allCategories: 'Все категории',
    searchProductsPlaceholder: 'Поиск по бренду, модели, серии или QR-коду',
    noProductsYet: 'Продуктов пока нет',
    noProductsYetDesc: 'Нажмите кнопку выше, чтобы добавить первый продукт',
    noProductsYetSyncDesc: 'Нажмите «Синхронизировать каталог EasyGas», чтобы загрузить каталог',
    noProductsMatch: 'Ничего не найдено',
    noProductsMatchDesc: 'Попробуйте изменить поиск или фильтры',
    unableToLoadProducts: 'Не удалось загрузить продукты',
    productCreated: 'Продукт успешно создан',
    productUpdated: 'Продукт успешно обновлён',
    productDeleted: 'Продукт удалён',
    productActivatedToast: 'Продукт активирован',
    productDeactivatedToast: 'Продукт деактивирован',
    activateAction: 'Активировать',
    deactivateAction: 'Деактивировать',
    activateProductTitle: 'Активировать продукт',
    activateProductMessage: 'Вы уверены, что хотите активировать этот продукт? Он снова появится в поиске.',
    deactivateProductTitle: 'Деактивировать продукт',
    deactivateProductMessage: 'Вы уверены, что хотите деактивировать этот продукт? Он больше не будет отображаться в поиске.',
    deleteProductTitle: 'Удалить продукт',
    deleteProductMessage: 'Вы уверены, что хотите удалить этот продукт? Это действие нельзя отменить.',
    productInStock: 'На складе',
    productInstalled: 'Установлен',
    productRetired: 'Списан',

    // ── Brands ──
    brands: 'Бренды',
    brandsSubtitle: 'Управление каталогом брендов продукции',
    createBrand: 'Добавить бренд',
    editBrand: 'Редактировать бренд',
    brandFullName: 'Полное название',
    country: 'Страна',
    logoUrl: 'URL логотипа',
    searchBrandsPlaceholder: 'Поиск по названию бренда',
    noBrandsYet: 'Брендов пока нет',
    noBrandsYetDesc: 'Нажмите кнопку выше, чтобы добавить первый бренд',
    noBrandsYetSyncDesc: 'Нажмите «Синхронизировать каталог EasyGas», чтобы загрузить каталог',
    noBrandsMatch: 'Ничего не найдено',
    noBrandsMatchDesc: 'Попробуйте изменить поиск',
    unableToLoadBrands: 'Не удалось загрузить бренды',
    brandCreated: 'Бренд успешно создан',
    brandUpdated: 'Бренд успешно обновлён',
    brandDeleted: 'Бренд удалён',
    brandActivatedToast: 'Бренд активирован',
    brandDeactivatedToast: 'Бренд деактивирован',
    activateBrandTitle: 'Активировать бренд',
    activateBrandMessage: 'Вы уверены, что хотите активировать этот бренд? Он снова появится в форме продукта.',
    deactivateBrandTitle: 'Деактивировать бренд',
    deactivateBrandMessage: 'Вы уверены, что хотите деактивировать этот бренд? Он больше не будет отображаться в форме продукта.',
    deleteBrandTitle: 'Удалить бренд',
    deleteBrandMessage: 'Вы уверены, что хотите удалить этот бренд? Это действие нельзя отменить.',
    brandInUseError: 'Этот бренд используется в продуктах и не может быть удалён — деактивируйте его',
    valBrandNameRequired: 'Введите название бренда',

    // ── Cars ──
    cars: 'Автомобили',
    carsSubtitle: 'Управление каталогом моделей автомобилей',
    createCar: 'Добавить автомобиль',
    editCar: 'Редактировать автомобиль',
    searchCarsPlaceholder: 'Поиск по марке или модели',
    noCarsYet: 'Автомобилей пока нет',
    noCarsYetDesc: 'Нажмите кнопку выше, чтобы добавить первый автомобиль',
    noCarsYetSyncDesc: 'Нажмите «Синхронизировать каталог EasyGas», чтобы загрузить каталог',
    noCarsMatch: 'Ничего не найдено',
    noCarsMatchDesc: 'Попробуйте изменить поиск',
    unableToLoadCars: 'Не удалось загрузить автомобили',
    carCreated: 'Автомобиль успешно создан',
    carUpdated: 'Автомобиль успешно обновлён',
    carDeleted: 'Автомобиль удалён',
    carActivatedToast: 'Автомобиль активирован',
    carDeactivatedToast: 'Автомобиль деактивирован',
    activateCarTitle: 'Активировать автомобиль',
    activateCarMessage: 'Вы уверены, что хотите активировать этот автомобиль? Он снова появится в поиске.',
    deactivateCarTitle: 'Деактивировать автомобиль',
    deactivateCarMessage: 'Вы уверены, что хотите деактивировать этот автомобиль? Он больше не будет отображаться в поиске.',
    deleteCarTitle: 'Удалить автомобиль',
    deleteCarMessage: 'Вы уверены, что хотите удалить этот автомобиль? Это действие нельзя отменить.',
    carInUseError: 'Этот автомобиль используется в гарантиях и не может быть удалён — деактивируйте его',
    valCarBrandRequired: 'Введите марку автомобиля',
    valCarModelRequired: 'Введите модель автомобиля',

    // ── EasyGas catalog sync (Products/Brands/Cars are read-only, synced from EasyGas) ──
    catalogSync: 'Синхронизация EasyGas',
    catalogSyncSubtitle: 'Синхронизация продуктов, брендов и автомобилей с EasyGas',
    catalogReadOnlyNotice: 'Этот каталог синхронизируется через EasyGas и не редактируется вручную. Для синхронизации перейдите на страницу:',
    syncCatalogButton: 'Синхронизировать каталог EasyGas',
    syncing: 'Синхронизация...',
    syncRunning: 'Выполняется...',
    lastSyncLabel: 'Последняя синхронизация',
    syncNeverRun: 'Ещё не синхронизировано',
    syncStatusSuccess: 'Успешно',
    syncStatusFailed: 'Не удалось',
    syncStatusRunning: 'Выполняется',
    syncDurationLabel: 'Длительность',
    syncInserted: 'Добавлено',
    syncUpdated: 'Обновлено',
    syncSkipped: 'Пропущено',
    syncFailed: 'Ошибка',
    syncProductsUpdated: 'Продукты обновлены',
    syncBrandsUpdated: 'Бренды обновлены',
    syncCarsUpdated: 'Автомобили обновлены',
    syncReasonNetwork: 'Не удалось подключиться к серверу EasyGas или истекло время ожидания',
    syncReasonHttpError: 'EasyGas вернул ошибку:',
    syncReasonUnknown: 'Неизвестная ошибка',

    // ── Inventory ──
    inventory: 'Склад',
    inventorySubtitle: 'Управление физическим запасом (штрих-кодами) для продуктов',
    inventoryImportAction: 'Импорт CSV',
    inventorySearchPlaceholder: 'Поиск по штрих-коду',
    inventoryBarcode: 'Штрих-код',
    inventoryCsvFile: 'CSV файл',
    inventoryStatusInStock: 'Доступно',
    inventoryStatusReserved: 'Зарезервировано',
    inventoryStatusInstalled: 'Установлено',
    inventoryStatusReturned: 'Возвращено',
    inventoryStatusDamaged: 'Повреждено',
    inventoryStatusLost: 'Утеряно',
    noInventoryYet: 'Записей склада пока нет',
    noInventoryYetDesc: 'Нажмите кнопку выше, чтобы импортировать первые штрих-коды',
    noInventoryMatch: 'Ничего не найдено',
    noInventoryMatchDesc: 'Попробуйте изменить поиск или фильтры',
    unableToLoadInventory: 'Не удалось загрузить склад',
    inventoryImported: 'Импортировано',
    inventorySkipped: 'Пропущено',
    inventoryDuplicates: 'Дубликаты',
    inventoryErrors: 'Ошибки',
    inventoryImportSuccess: 'Импорт успешно завершён',

    // ── Installer points ──
    points: 'Баллы',
    myPoints: 'Мои баллы',
    myPointsSubtitle: 'История начисленных и возвращённых баллов за каждую установленную единицу оборудования',
    installerPoints: 'Баллы установщиков',
    installerPointsSubtitle: 'Просмотр истории баллов установщика и создание ручных корректировок',
    pointsConfig: 'Настройка баллов',
    pointsConfigSubtitle: 'Задайте количество баллов для каждого продукта — изменение влияет только на будущие гарантии',
    totalPoints: 'Всего баллов',
    pointsHistory: 'История баллов',
    noPointsYet: 'Записей о баллах пока нет',
    noPointsYetDesc: 'Баллы появятся здесь после подачи гарантии',
    unableToLoadPoints: 'Не удалось загрузить баллы',
    pointValueLabel: 'Количество баллов',
    savePointValue: 'Сохранить',
    pointValueUpdated: 'Количество баллов обновлено',
    selectInstallerPlaceholder: 'Выберите установщика',
    searchInstallerPlaceholder: 'Поиск по установщику',
    manualAdjustment: 'Ручная корректировка',
    createAdjustment: 'Создать корректировку',
    adjustmentType: 'Тип',
    adjustmentPoints: 'Количество баллов',
    adjustmentReason: 'Причина',
    adjustmentReasonPlaceholder: 'Почему создаётся эта корректировка?',
    bonusLabel: 'Бонус',
    penaltyLabel: 'Штраф',
    adjustmentLabel: 'Корректировка',
    adjustmentCreated: 'Корректировка успешно создана',
    pointsTypeWarrantyAward: 'Начисление за гарантию',
    pointsTypeWarrantyReversal: 'Возврат баллов',
    pointsTypeManualAdjustment: 'Ручная корректировка',
    pointsTypeManualBonus: 'Бонус',
    pointsTypeManualPenalty: 'Штраф',
    pointsDateColumn: 'Дата',
    pointsReasonColumn: 'Причина',
    pointsAmountColumn: 'Баллы',
    pointsTypeColumn: 'Тип',
    selectAnInstaller: 'Выберите установщика, чтобы увидеть историю баллов',
    superAdminOnlyHint: 'Только Супер Админ может изменять количество баллов и создавать корректировки',
    typedCylinderPointValue: 'Баллон без каталога',
    typedCylinderPointValueHint: 'Количество баллов за баллон, введённый вручную, без выбора из каталога',
    typedCylinderLabel: 'Баллон без каталога',

    // ── Phase 4: inventory filters, manual operations ──
    inventoryStatusMerged: 'Объединено',
    filterByInstaller: 'Установщик',
    filterByWarehouse: 'Склад',
    filterByImportBatch: 'Партия импорта',
    installedFromLabel: 'Дата установки от',
    installedToLabel: 'Дата установки до',
    claimedFromLabel: 'Дата закрепления от',
    claimedToLabel: 'Дата закрепления до',
    advancedFilters: 'Дополнительные фильтры',
    warehouseLabel: 'Склад',
    allWarehouses: 'Все склады',
    unassignedWarehouse: 'Не назначен',
    manualOperations: 'Ручные операции',
    changeStatusAction: 'Изменить статус',
    transferBranchAction: 'Переместить на другой склад',
    correctBarcodeAction: 'Исправить штрих-код',
    mergeDuplicateAction: 'Объединить дубликат',
    newStatusLabel: 'Новый статус',
    newBarcodeLabel: 'Новый штрих-код',
    canonicalItemLabel: 'Основной товар (штрих-код)',
    reasonLabel: 'Причина',
    reasonPlaceholderGeneric: 'Почему выполняется это действие?',
    operationSuccess: 'Операция успешно выполнена',
    confirmMergeTitle: 'Подтвердите объединение дубликата',
    confirmMergeMessage: 'Этот товар будет объединён с основным, и это действие нельзя отменить. Продолжить?',

    // ── Phase 4: reports dashboard ──
    reportsDashboard: 'Панель отчётов',
    totalProductsLabel: 'Всего продуктов',
    totalInventoryLabel: 'Всего товаров на складе',
    installedProductsLabel: 'Установленные продукты',
    availableInventoryLabel: 'Доступный запас',
    damagedInventoryLabel: 'Повреждённый запас',
    lostInventoryLabel: 'Утерянный запас',
    returnedInventoryLabel: 'Возвращённый запас',
    importedTodayLabel: 'Импортировано сегодня',
    importedThisMonthLabel: 'Импортировано за месяц',
    topInstalledProductsLabel: 'Самые устанавливаемые продукты',
    topWarehousesLabel: 'Крупнейшие склады',
    pointsLeaderboardLabel: 'Рейтинг по баллам',
    recentImportsLabel: 'Последние импорты',
    recentWarrantyActivityLabel: 'Последняя активность по гарантиям',
    recentInventoryActivityLabel: 'Последняя активность склада',

    // ── Phase 4: statistics pages ──
    installerStatistics: 'Статистика установщика',
    productStatistics: 'Статистика продукта',
    warehouseStatistics: 'Статистика склада',
    myStatistics: 'Моя статистика',
    monthlyPoints: 'Баллы за месяц',
    lifetimePoints: 'Баллы за всё время',
    totalClaimedInventoryLabel: 'Всего закреплённых товаров',
    activityGraphLabel: 'График активности',
    importedQuantityLabel: 'Импортировано',
    installedQuantityLabel: 'Установлено',
    remainingStockLabel: 'Остаток на складе',
    failureRateLabel: 'Процент брака',
    returnRateLabel: 'Процент возвратов',
    topBranchesLabel: 'Самые активные филиалы',
    currentStockLabel: 'Текущий запас',
    installedStockLabel: 'Установленный запас',
    reservedStockLabel: 'Зарезервированный запас',
    movementHistoryLabel: 'История перемещений',
    selectProductPlaceholder: 'Выберите продукт',
    selectWarehousePlaceholder: 'Выберите склад',
    exportCsvAction: 'Экспорт в CSV',
    exportingCsv: 'Экспортируется...',

    valCategoryRequired: 'Выберите категорию',
    valBrandRequired: 'Выберите бренд',
    valSerialRequired: 'Введите серийный номер',
    valScoreInvalid: 'Баллы должны быть целым числом не меньше 0',
    productCodeLabel: 'Серийный номер или QR-код',
    productCodePlaceholder: 'Введите или отсканируйте код',
    addProduct: 'Добавить',
    productAlreadyAdded: 'Этот продукт уже добавлен',
    removeProduct: 'Убрать продукт',
    legacyEquipmentTitle: 'Ранее записанное оборудование',
    legacyEquipmentDesc: 'Введено до внедрения учёта продукции (только для чтения)',
    valProductsRequired: 'Добавьте хотя бы один продукт',

    // ── Reports ──
    reports: 'Отчёты',
    reportsSubtitle: 'Рейтинг установщиков, филиалов и продукции',
    unableToLoadReports: 'Не удалось загрузить отчёты',
    totalWarrantiesInPeriod: 'Гарантий за период',
    totalEquipmentInstalled: 'Всего установленного оборудования',
    topInstallers: 'Лучшие установщики',
    branchRanking: 'Рейтинг филиалов',
    productsInstalledTitle: 'Установленные продукты',
    monthlyActivityTitle: 'Динамика активности по месяцам',
    warrantyCount: 'Количество гарантий',
    noReportDataYet: 'Данных пока нет',
    noReportDataYetDesc: 'Появятся здесь после подачи гарантийных форм с продуктами',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('ezone_language');
    return saved || 'uz';
  });

  useEffect(() => {
    localStorage.setItem('ezone_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'uz' ? 'ru' : 'uz');
  };

  return (
    <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
